# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  connect:
    image: connect
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 443:443
      - 80:80
